DANS-KNAW/dd-ingest-flow

src/main/scala/nl.knaw.dans.easy.dd2d/mapping/FileElement.scala
src/test/scala/nl.knaw.dans.easy.dd2d/mapping/FileElementSpec.scala

Fixes DD-885
* Applies the same replacement rules for `label` and `directoryLabel` as `easy-fedora-to-bag`.
* If the sanitized `label` or `directoryLabel` is different from the original than a new pseudo-property is added to the description: `original_filepath`. 
* Ingest files with forbidden chars in directory path or filename.

DD-885 Remove forbidden characters from directory-path and filenames in exported bag-store datasets

---

src/main/assembly/dist/bin/ingest-flow
src/main/assembly/dist/cfg/config.yml
src/main/assembly/dist/install/dd-ingest-flow.service
src/main/java/nl/knaw/dans/ingest/DdIngestFlowApplication.java
src/main/java/nl/knaw/dans/ingest/api/StartImport.java
src/main/java/nl/knaw/dans/ingest/core/AbstractIngestArea.java
src/main/java/nl/knaw/dans/ingest/core/AutoIngestArea.java
src/main/java/nl/knaw/dans/ingest/core/ImportArea.java
src/main/java/nl/knaw/dans/ingest/core/config/IngestAreaConfig.java
src/main/java/nl/knaw/dans/ingest/core/config/IngestFlowConfig.java
src/main/java/nl/knaw/dans/ingest/resources/MigrationsResource.java

Fixes DD-900
* Adds a new configuration section to configure the migration area.
* Renames "inboxes" into "ingest areas" to make it a bit more logical, because these "ingest areas" contain an inbox and outbox.
* Adds a `start-migration` subcommand and removes the `--migration` flag from `start-import`.
* https://github.com/DANS-KNAW/dd-dtap/pull/213

DD-900. Separate import and migration areas

---

src/main/scala/nl.knaw.dans.easy.dd2d/DepositIngestTask.scala
src/main/scala/nl.knaw.dans.easy.dd2d/DepositMigrationTask.scala
src/main/scala/nl.knaw.dans.easy.dd2d/DepositToDvDatasetMetadataMapper.scala

Fixes DD-901
* For non-migration deposits fill in `Unknown` if agreements.xml is not found.
* For migration deposits reject the deposit if agreements.xml is not found.
* Test a SWORD deposit and a migration deposit without agreements.xml

DD-901. use Has Personal Info = unknown if not specified by client in auto-ingest

---

src/main/java/nl/knaw/dans/ingest/db/TaskEventDAO.java
src/main/scala/nl.knaw.dans.easy.dd2d/Deposit.scala
src/main/scala/nl.knaw.dans.easy.dd2d/DepositIngestTask.scala
src/main/scala/nl.knaw.dans.easy.dd2d/DepositToDvDatasetMetadataMapper.scala
src/main/scala/nl.knaw.dans.easy.dd2d/mapping/DepositPropertiesOtherDoi.scala
src/test/resources/examples/doi-and-no-other-doi/bag/bag-info.txt
src/test/resources/examples/doi-and-no-other-doi/bag/bagit.txt
src/test/resources/examples/doi-and-no-other-doi/bag/manifest-md5.txt
src/test/resources/examples/doi-and-no-other-doi/bag/tagmanifest-md5.txt
src/test/resources/examples/doi-and-no-other-doi/deposit.properties
src/test/resources/examples/doi-and-other-doi/bag/bag-info.txt
src/test/resources/examples/doi-and-other-doi/bag/bagit.txt
src/test/resources/examples/doi-and-other-doi/bag/manifest-md5.txt
src/test/resources/examples/doi-and-other-doi/bag/tagmanifest-md5.txt
src/test/resources/examples/doi-and-other-doi/deposit.properties
src/test/resources/examples/no-doi-in-vault-metadata/bag/bag-info.txt
src/test/resources/examples/no-doi-in-vault-metadata/bag/bagit.txt
src/test/resources/examples/no-doi-in-vault-metadata/bag/manifest-md5.txt
src/test/resources/examples/no-doi-in-vault-metadata/bag/tagmanifest-md5.txt
src/test/resources/examples/no-doi-in-vault-metadata/deposit.properties
src/test/scala/nl.knaw.dans.easy.dd2d/DepositSpec.scala
src/test/scala/nl.knaw.dans.easy.dd2d/DepositToDataverseMapperSpec.scala

Fixes DD-825
If a DOI is provided in the `deposit.properties` via the `dataverse.id-*` properties (this will happen only during migration) and it is different from `identifier.doi` then we conclude that `identifier.doi` is the version-specific DOI minted in EASY and add `identifier.doi` as an Other ID in the Citation Metadata. I have used the prefix `doi:` there to keep consistency with the way Dataverses displays the main DOI of the dataset.
* Import a migration deposit for which the two properties differ (the Other ID should be added)
* Import a migration deposit for which the two properties are the same (should not be added)
* Import a non-migration deposit (should not be added).

DD-825 Add doi of second-version as Other Identifier in Dataverse

---

src/main/scala/nl.knaw.dans.easy.dd2d/DepositToDvDatasetMetadataMapper.scala
src/main/scala/nl.knaw.dans.easy.dd2d/mapping/Description.scala

Fixes DD-803
* `dcmiMetadata / description` is now added as a description if it has an attribute `descriptionType = TechnicalInfo`.
* Other `dcmiMetadata / description` elements are now ignored, as per specs.

DD-803 Add TechnicalInfo as description

---

src/main/scala/nl.knaw.dans.easy.dd2d/DepositToDvDatasetMetadataMapper.scala

Fixes DD-859
Sort values of multi-value controlledVocabulary field
Import a deposit with multiple subjects or languages, given in non-alphabetical order.

DD-859. Sort values of multi-value controlledVocabulary field

---

src/main/scala/nl.knaw.dans.easy.dd2d/DepositToDvDatasetMetadataMapper.scala
src/main/scala/nl.knaw.dans.easy.dd2d/mapping/Publisher.scala
src/test/scala/nl.knaw.dans.easy.dd2d/DepositToDataverseMapperSpec.scala

Fixes DD-968
Normally `dcmiMetadata / publisher` is mapped to a `distributor` (with only the name subfield filled in). This PR skips this mapping if the publisher is `DANS`, `DANS-KNAW` or `DANS/KNAW`.
* Added unit tests to `src/test/scala/nl.knaw.dans.easy.dd2d/DepositToDataverseMapperSpec.scala`.

DD-968. not mapping DANS and DANS-KNAW values in publisher

---

src/main/scala/nl.knaw.dans.easy.dd2d/DepositToDvDatasetMetadataMapper.scala

Fixes DD-993
Add `dcmiMetadata/description` elements without the descriptionType = TechnicalInfo. 
Import a deposit that has `dcmiMetadata/description` elements without attributes and check that the descriptions are added as Dataverse Citation Metadata descriptions.

DD-993 dd-ingest-flow skips non TechInfo descriptions under dcmiMetadata

---

src/main/scala/nl.knaw.dans.easy.dd2d/DepositIngestTask.scala
src/main/scala/nl.knaw.dans.easy.dd2d/DepositMigrationTask.scala
src/main/scala/nl.knaw.dans.easy.dd2d/dansbag/DansBagValidator.scala
src/main/scala/nl.knaw.dans.easy.dd2d/mapping/Description.scala

Fixes DD-995
* Made sure `dd-ingest-flow` always uses DANS BagIt Profile version 1
* Migration tasks use the AIP rules
* Import tasks (SWORD2, bulk-import) use the SIP rules.
https://github.com/DANS-KNAW/easy-validate-dans-bag/pull/115

DD-995 Use DANS BagIt Profile v1

---

pom.xml
src/main/scala/nl.knaw.dans.easy.dd2d/DatasetCreator.scala
src/main/scala/nl.knaw.dans.easy.dd2d/DatasetEditor.scala
src/main/scala/nl.knaw.dans.easy.dd2d/DatasetUpdater.scala
src/main/scala/nl.knaw.dans.easy.dd2d/DepositIngestTask.scala
src/main/scala/nl.knaw.dans.easy.dd2d/DepositMigrationTask.scala
src/test/resources/debug-etc/config.yml

Fixes DD-999: part 3 - replace dataverse library (scala to java) 

DD-999: part 3 - replace dataverse library (scala to java) 

---

pom.xml
src/main/java/nl/knaw/dans/ingest/core/legacy/MapperForScala.java
src/main/scala/nl.knaw.dans.easy.dd2d/DatasetCreator.scala
src/main/scala/nl.knaw.dans.easy.dd2d/DatasetEditor.scala
src/main/scala/nl.knaw.dans.easy.dd2d/DatasetUpdater.scala
src/main/scala/nl.knaw.dans.easy.dd2d/DepositIngestTask.scala
src/main/scala/nl.knaw.dans.easy.dd2d/DepositMigrationTask.scala

Fixes DD-999: part 4 - replace dataverse library (scala to java)
As in https://github.com/DANS-KNAW/dd-ingest-flow/pull/20 but make sure 
* https://github.com/DANS-KNAW/dans-dataverse-client-lib/pull/26

DD-999: part 4 - replace dataverse library (scala to java)

---

src/main/assembly/dist/cfg/config.yml
src/main/scala/nl.knaw.dans.easy.dd2d/DepositIngestTask.scala
src/main/scala/nl.knaw.dans.easy.dd2d/DepositMigrationTask.scala
src/main/scala/nl.knaw.dans.easy.dd2d/dansbag/DansBagValidationCommand.scala
src/main/scala/nl.knaw.dans.easy.dd2d/dansbag/DansBagValidationResult.scala
src/main/scala/nl.knaw.dans.easy.dd2d/dansbag/DansBagValidator.scala
src/main/scala/nl.knaw.dans.easy.dd2d/dansbag/RuleViolation.scala

Fixes DD-1011
* Added case classes to represent the command object to send to `dd-validate-dans-bag`.
* Changed the default URL of the validator service.

DD-1011 Adapted call to validator for new interface of dd-validate-dans-bag

---

src/main/java/nl/knaw/dans/ingest/core/AbstractIngestArea.java
src/main/java/nl/knaw/dans/ingest/core/ImportArea.java
src/main/java/nl/knaw/dans/ingest/resources/ImportsResource.java
src/main/java/nl/knaw/dans/ingest/resources/MigrationsResource.java

Fixes DD-1144
When een import is started, the service now first checks whether input directory is a deposit (when isBatch = false) or a directory containing only deposits (when isBatch = true). This check is done synchronously, so that the client gets the result when the start call returns.

DD-1144 Input validation of startImport

---

pom.xml

Fixes DD-1131
Upgraded parent pom, and in doing so `dans-dataverse-client-lib`
* [ Metadata character encoding problems on test_ssh migration](https://github.com/DANS-KNAW/dans-dataverse-client-lib/pull/33)

DD-1131 Metadata character encoding problems on test_ssh migration

---

src/main/java/nl/knaw/dans/ingest/core/service/DansBagValidatorImpl.java

Fixes DD-
readEntity was read twice causing the service to report unhealty
https://dans-knaw.github.io/dd-ingest-flow/dev/
(Add links)
*

DD-1199: health check - dropped too early readEntity

---

src/main/java/nl/knaw/dans/ingest/core/service/DepositIngestTask.java

Fixes DD-1238
In a single case, when an exception during publishing of a dataset, it would only log the error but not propagate the error. The code would assume everything went OK despite the publishing having failed. 
All other catch clauses have also been checked for swallowing errors, but no other cases could be identified that were not by design.
(Add links)
*

Rethrow exception

---

pom.xml
src/main/java/nl/knaw/dans/ingest/core/service/DatasetCreator.java
src/main/java/nl/knaw/dans/ingest/core/service/DatasetEditor.java
src/main/java/nl/knaw/dans/ingest/core/service/DatasetUpdater.java
src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapper.java
src/main/java/nl/knaw/dans/ingest/core/service/mapper/mapping/FileElement.java

NO JIRA
Several fixes:
* Upgraded to dans-dataverse-client-lib 0.12.0 for support for restrict(ed) property. Corrected ns in lookup of accessibleToRights and added default accessTerms (for now)
* More flexible parsing of available dates. Fix for excluding easy-migration.zip from embargo in updates
* Rename refactorings + zipwrapping for replaceFile
* Replace java.time.format.DateTimeFormatter with SimpleDateFormat for converting embargo Instant back to date string. DateTimeFormatter resulted in unsuppoert field 'YearOfEra'
* hsqldb back to v2.5.0 (temporarily)

Rename refactorings + zipwrapping for replaceFile

---

debug-init-env.sh
src/main/java/nl/knaw/dans/ingest/DdIngestFlowConfiguration.java
src/main/java/nl/knaw/dans/ingest/core/service/AbstractDepositsImportTaskIterator.java
src/main/java/nl/knaw/dans/ingest/core/service/BoundedDepositImportTaskIterator.java
src/main/java/nl/knaw/dans/ingest/core/service/UnboundedDepositsImportTaskIterator.java
src/test/java/nl/knaw/dans/ingest/core/DepositStartImportTaskWrapperTest.java
src/test/resources/debug-etc/config.yml

Fixes DD-1249
* When initially filling the queue sort tasks on Created timestamp before adding them to the queue.
* Faulty config will fail fast now, because of `@NonNull` annotations.

DD-1249  Sort deposits on Created timestamp when reading all from inbox

---

src/main/java/nl/knaw/dans/ingest/DdIngestFlowApplication.java
src/main/java/nl/knaw/dans/ingest/core/ImportArea.java
src/main/java/nl/knaw/dans/ingest/resources/ImportsResource.java
src/main/java/nl/knaw/dans/ingest/resources/MigrationsResource.java

NO JIRA
The `ImportArea` class is used for both "bulk imports" and "migrations". It is instantiated twice during application initialization: 1) as `importArea` and as `migrationArea`. In both cases it was given two task factories: one for bulk import tasks and one for migration tasks. Since each of the areas is dedicated to only one type of task it would only ever use one of those factories. 
Refactored this, so that `ImportArea` receives only one factory; `nl.knaw.dans.ingest.DdIngestFlowApplication#run` makes sure it is the correct one. The resource classes now don't have to pass the `isMigration` parameter anymore.
Also remove a `batches` map that was updated but never read.
*

Refactored away unnecessary boolean 'isMigration'

---

src/main/java/nl/knaw/dans/ingest/core/service/DansBagValidator.java
src/main/java/nl/knaw/dans/ingest/core/service/DansBagValidatorImpl.java
src/main/java/nl/knaw/dans/ingest/core/service/DepositIngestTask.java
src/main/java/nl/knaw/dans/ingest/core/service/DepositMigrationTask.java

Fixes DD-1245
* `dd-validate-dans-bag` will now be called `WITH-DATA-STATION-CONTEXT` for SWORD2 and bulk-import deposits and still `STAND-ALONE` for migration deposits.
1. Build and install the latest `dd-sword2` and `dd-ingest-flow` (this PR)
2. Assign the swordcreator role to a user
3. Do a SWORD deposit for that user with `dd-dans-sword2-examples`.

DD-1245 dd-ingest-flow should call dd-validate-dans-bag WITH-DATASTATION-CONTEXT level

---

pom.xml
src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapper.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/MappingIntegrationTest.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/mapping/AuthorTest.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/mapping/ContributorTest.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/mapping/DatesOfCollectionTest.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/mapping/DcxDaiAuthorTest.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/mapping/DcxDaiOrganizationTest.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/mapping/DepositPropertiesVaultMetadataTest.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/mapping/DescriptionTest.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/mapping/IdentifierTest.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/mapping/RelationTest.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/mapping/SpatialBoxTest.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/mapping/SpatialPointTest.java

Fixes DD-1255: upgrade dans-dataverse-client-lib: requires casts in test classes

DD-1255: upgrade dans-dataverse-client-lib: requires casts in test classes

---

src/main/java/nl/knaw/dans/ingest/core/service/Deposit.java
src/main/java/nl/knaw/dans/ingest/core/service/DepositIngestTask.java
src/main/java/nl/knaw/dans/ingest/core/service/ManifestHelper.java
src/main/java/nl/knaw/dans/ingest/core/service/mapper/mapping/FileElement.java
src/test/java/nl/knaw/dans/ingest/core/service/ManifestHelperTest.java

Fixes DD-1171: add SHA1 manifest if not present
* add SHA1 manifest if not present
* update tagmanifest
* moved a static method from the `FileEment` class to the new `ManifestHelper` class
(Add links)
*

DD-1171: add SHA1 manifest if not present

---

src/main/assembly/dist/cfg/spatial-coverage-country-terms.txt
src/main/java/nl/knaw/dans/ingest/DdIngestFlowApplication.java
src/main/java/nl/knaw/dans/ingest/IngestFlowConfigReader.java
src/main/java/nl/knaw/dans/ingest/core/config/IngestFlowConfig.java
src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapper.java
src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapperFactory.java
src/main/java/nl/knaw/dans/ingest/core/service/mapper/mapping/SpatialCoverage.java
src/test/java/nl/knaw/dans/ingest/DdIngestFlowConfigurationTest.java
src/test/java/nl/knaw/dans/ingest/core/DepositStartImportTaskWrapperTest.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapperTest.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/MappingIntegrationTest.java
src/test/resources/debug-etc/spatial-coverage-country-terms.txt

Fixes DD-1282: configurable languages for SpatialCoverage
as documented with 
<ddm:dcmiMetadata>
<dct:spatial>Tunisia</dct:spatial>
<dct:spatial>Nederland</dct:spatial>
...
(Add links)
*

DD-1282: configurable languages for SpatialCoverage

---

src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapper.java
src/main/java/nl/knaw/dans/ingest/core/service/mapper/builder/CitationFieldBuilder.java
src/main/java/nl/knaw/dans/ingest/core/service/mapper/builder/FieldBuilder.java
src/main/java/nl/knaw/dans/ingest/core/service/mapper/mapping/Description.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/MappingIntegrationTest.java

Fixes DD-1292: map multiple Series-information to single compound field
(Add links)
*

DD-1292: map multiple Series-information to single compound field

---

pom.xml
src/main/java/nl/knaw/dans/ingest/core/domain/Deposit.java
src/main/java/nl/knaw/dans/ingest/core/service/DatasetCreator.java
src/main/java/nl/knaw/dans/ingest/core/service/DatasetEditor.java
src/main/java/nl/knaw/dans/ingest/core/service/DatasetUpdater.java
src/main/java/nl/knaw/dans/ingest/core/service/DepositIngestTask.java
src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapper.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/CitationMetadataFromProfileTest.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapperTest.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/MappingIntegrationTest.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/MappingTestHelper.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/RightsMetadataTest.java

NO JIRA
Dataverse's `TermsOfUseAndAccessValidator` was giving errors because the terms of access were not always filled in when fileAccessRequests was off. Part of the reason was that updating the metadata by the DatasetUpdater was overwriting termOfAccess with null. See also: https://github.com/DANS-KNAW/dans-dataverse-client-lib/pull/41 
The logic that determined whether to allow access requests and whether to set terms of access was also spread out too much.
* Moved the code that determines whether to allow access requests and whether there are restricted files present to the Deposit class for now: 
* `allowAccessRequests` is only based on the what the deposit knows. The code that actually turns access requests on or off inspects the current state (only in updates of course) to make …

Solve TermsOfAccess validation error

---

src/main/java/nl/knaw/dans/ingest/core/service/DatasetUpdater.java

NO JIRA.
When doing a file replacement, the metadata for the file used to have empty fields, as the metadata of **all** files is updated later in the process anyway. A side effect of this was that the filename from then Content-Disposition header was used to determine the initial filename. In one case the name contained a "`" (back-tick) character. At the Dataverse side this was replaced with a question mark which is a forbidden character for a file label, so Dataverse returned "400 could not add file" (it was a replacement, but anyway...).
Setting the encoding of the Content-Disposition headers seems hard to achieve. See for example [this post](https://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http), although it is a bit old. …

NO JIRA. Work-around for non-ascii char in replacement file name

---

src/main/assembly/dist/cfg/config.yml
src/main/java/nl/knaw/dans/ingest/core/config/ValidateDansBagConfig.java
src/test/resources/debug-etc/config.yml
src/test/resources/unit-test-config.yml

NO JIRA
* The configuration block `validateDansBag` contained two settings that were not used: `connectionTimeoutMs`, `readTimeoutMs`.   
The nested `httpClient` contains parameters that control these timeouts. Removed the redundant settings.
* Tried out if Lombok will work together with DropWizard by lombokifying the `ValidateDansBagConfig` class.

Removed unused config settings

---

src/main/java/nl/knaw/dans/ingest/DdIngestFlowApplication.java

Fixes DD-1338
Amends #97 removing the separate health check for each dataverse client. The health check only accesses the root dataverse anyway, so there is no added value in trying it with different API keys. No API key is required at all.
Also implemented defaulting to the API key configured on the `dataverse` block in the config file, which was missing.
* #97 

DD-1338 API key per ingest area

---

pom.xml
src/main/assembly/dist/cfg/config.yml
src/main/java/nl/knaw/dans/ingest/core/config/IngestFlowConfig.java
src/main/java/nl/knaw/dans/ingest/core/service/DatasetCreator.java
src/main/java/nl/knaw/dans/ingest/core/service/DatasetEditor.java
src/main/java/nl/knaw/dans/ingest/core/service/DatasetUpdater.java
src/main/java/nl/knaw/dans/ingest/core/service/DepositIngestTask.java
src/main/java/nl/knaw/dans/ingest/core/service/DepositIngestTaskFactory.java
src/main/java/nl/knaw/dans/ingest/core/service/DepositMigrationTask.java
src/main/java/nl/knaw/dans/ingest/core/service/mapper/mapping/FileElement.java
src/test/java/nl/knaw/dans/ingest/core/DepositStartImportTaskWrapperTest.java
src/test/java/nl/knaw/dans/ingest/core/service/DatasetEditorTest.java
src/test/java/nl/knaw/dans/ingest/core/service/DepositIngestTaskTest.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/mapping/FileElementTest.java

Fixes DD-1442
In reality DD-1442 will have to be fixed in Dataverse, but I am classifying this PR under DD-1442 because the fixes in it were found while investigating and testing DD-1442. 
* Made `deleteDraftOnFailure` a configuration option. During testing you may want to keep the draft resulting from a failed deposit around, in order to be able to analyze the problem better.
* Fixed a problem in `FileElement.toFileMeta` which caused huge descriptions when there where `keyvaluepair` elements.
* Saving the DOI to `deposit.properties` prefixed it with `doi:`, in Dataverse style. However, this caused multiple `doi:` prefixes when retrying the same deposits. `identfier.doi` is now stored without the prefix, the way it is also found in a migration deposit. Furthermore, it is only stored in a …

DD-1442 Ingest-problems Dataverse v5.14

---

src/main/java/nl/knaw/dans/ingest/core/service/mapper/mapping/Contributor.java

* Fix errors in contributorRole mapping. 
* 'RelatedPerson' was written as 'Related Person' as DataCite 4 term, which would not match.  
* The 'ProjectMember' contributorType was not mapped, even though DataCite 3 / Dataverse does have this role.
* Added some comments to clarify the mapping.

NO JIRA. Fix errors in contributorRole mapping.

---

src/main/java/nl/knaw/dans/ingest/core/deposit/DepositFileListerImpl.java
src/main/java/nl/knaw/dans/ingest/core/domain/Deposit.java
src/main/java/nl/knaw/dans/ingest/core/service/DatasetEditor.java
src/main/java/nl/knaw/dans/ingest/core/service/XPathConstants.java
src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapper.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/mapping/RelationTest.java

Fixes DD-1461
I forgot the `ddm` prefix for `ddm:dcmiMetadata` here: https://github.com/DANS-KNAW/dd-ingest-flow/compare/master...janvanmansum:dd-ingest-flow:DD-1461b?expand=1#diff-745b51a7500fd6ed9124c8d4d697b0e785d98e5755aa155d3581807a5c303536L429 which was a really hard-to-spot bug. Fixed this and also made the often-used expression prefixed `/ddm:DDM/profile` and `/ddm:DDM/ddm:dcmiMetadata` into constants to prevent this from happening again.
(Add links)
*

DD-1461. Fixed error in expression + added constants for often used expression prefixes

---

src/main/java/nl/knaw/dans/ingest/core/dataverse/DatasetService.java
src/main/java/nl/knaw/dans/ingest/core/dataverse/DataverseServiceImpl.java
src/main/java/nl/knaw/dans/ingest/core/service/DepositIngestTask.java

Fixes DD-1445
Now that datasets deposited through SWORD2 may be submitted for review, update-deposits need to check that the targeted dataset is not In Review before proceeding.

DD-1445 Add check on InReview status for update-deposits

---

src/main/java/nl/knaw/dans/ingest/core/service/DepositIngestTask.java

NO JIRA
When a dataset is going through through the ingest-flow through a user without swordpublisher privileges, the DOI should still be returned. The dataset-version will end up "In review" but Dataverse has already assigned a DOI to it and updated DataCite, so returning the DOI is useful.

NO JIRA. Return DOI for datasets that are submitted for review

---

.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/coverage.yml
src/main/java/nl/knaw/dans/ingest/core/service/DatasetUpdater.java
src/main/java/nl/knaw/dans/ingest/core/service/DepositIngestTask.java
src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapper.java

Fixes DD-1490
* For new non-migration datasets the `dateOfDeposit` is set to the date of today.
* For update-deposits, the `dateOfDeposit` is copied from the previous version. (It is not inherited automatically, as the update code overwrites the complete dataset metadata.)
Deploy to `dev_archaeology`, then in `dd-dans-sword2-examples`:
```
./run-simple-deposit.sh https://dev.sword2.archaeology.datastations.nl/collection/1 user001 user001 src/main/resources/example-bags/valid/all-mappings
```
This adds a dataset. Verify that the deposit date is set to the current date.
Now change the deposit date in the database:
```
vagrant ssh
psql -U dvnuser dvndb # pw dvnsecret
select * from datasetfieldvalue where value = '<current-date>'; # e.g. 2024-01-25
```
This should give you only one row in an …

DD-1490 CIT025B date of deposit for new sword deposit.

---

src/main/java/nl/knaw/dans/ingest/core/service/DatasetCreator.java
src/main/java/nl/knaw/dans/ingest/core/service/DatasetEditor.java
src/main/java/nl/knaw/dans/ingest/core/service/DatasetUpdater.java

When an ingest fails, any draft dataset version that was created is deleted if the setting `deleteOfFailure` is set to true. This was not correctly implemented yet for new datasets (only for updates).
@DANS-KNAW/core-systems

NO JIRA. Add missing draft deletion action

---

pom.xml
src/main/java/nl/knaw/dans/ingest/core/deposit/DepositLocationReaderImpl.java
src/main/java/nl/knaw/dans/ingest/core/service/DepositIngestTaskFactoryBuilder.java
src/test/java/nl/knaw/dans/ingest/core/DepositStartImportTaskWrapperTest.java
src/test/java/nl/knaw/dans/ingest/core/deposit/DepositLocationReaderImplTest.java

Fixes DD-1539
Replaced `Created` from `bag-info.txt` with `creation.timestamp` from `deposit.properties` as the value on which to sort deposits on service start-up. `Created` from `bag-info.txt` is being phased out and will be ignored.
@DANS-KNAW/core-systems

DD-1539 Get 'Created' timestamp from deposit.properties instead of bag-info.txt

---

pom.xml

Fixes DD-1565
Use dd-parent 1.5.0 with updated client lib for dataverse 6.2
(Add links)
*https://github.com/DANS-KNAW/dd-validate-dans-bag/pull/54
*https://github.com/DANS-KNAW/dd-vault-metadata/pull/13
@DANS-KNAW/core-systems

Use dd-parent 1.5.0 with updated client lib for dataverse 6.2

---

src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapper.java
src/main/java/nl/knaw/dans/ingest/core/service/mapper/builder/CitationFieldBuilder.java
src/test/java/nl/knaw/dans/ingest/core/service/mapper/CitationMetadataFromDcmiTest.java

Fixes DD-1566
Start the archaeology dev box
```
start-preprovisioned-box.py -s        
```
Then deploy the upgrade to 6.2
```
deploy.py --playbook provisioning/patches/upgrade-dataverse/to-6.2.yml dev_archaeology
```
For now upgrade these modules because that is not part of the `to-6.2` yet
```
deploy.py -t dd-vault-metadata dev_archaeology
deploy.py -t dd-validate-dans-bag dev_archaeology
deploy.py -t dd-ingest-flow dev_archaeology
```
Go to the sword2 examples:
`~/git/dans-core-systems/modules/dd-dans-sword2-examples` and run the one we know that fails: 
```
./run-simple-deposit.sh https://dev.sword2.archaeology.datastations.nl/collection/1 user001 user001  src/main/resources/example-bags/valid/all-mappings
```
That should fail, we have not updated the ingest flow with our PR!
Next us …

DD-1566: fix multiplicity alternative title
