src/main/java/nl/knaw/dans/ingest/resources/EventsResource.java
Fixes DD-906
* Send the charset with the response, so the client can use the correct one to decode it.
=> DD-906. server-side solution

src/main/scala/nl.knaw.dans.easy.dd2d/DepositToDvDatasetMetadataMapper.scala, src/main/scala/nl.knaw.dans.easy.dd2d/mapping/DcxDaiOrganization.scala, src/test/scala/nl.knaw.dans.easy.dd2d/mapping/DcxDaiOrganizationSpec.scala
Fixes DD-790
A Contributor that is an organization and has role Funder is now added as a "Grant Number" with only an Agency subfield.
=> DD-790 Grant number from funder contributor organization

pom.xml, src/main/scala/nl.knaw.dans.easy.dd2d/DatasetCreator.scala, src/main/scala/nl.knaw.dans.easy.dd2d/DatasetEditor.scala, src/main/scala/nl.knaw.dans.easy.dd2d/DatasetUpdater.scala
Fixes DD-999: part 2 - new methods called by dd-ingest-flow.DatasetCreator
build also related PR and continue as for https://github.com/DANS-KNAW/dd-ingest-flow/pull/20
=> DD-999: part 2 - new methods called by dd-ingest-flow.DatasetCreator

debug-init-env.sh, docs/dev.md, pom.xml, src/test/resources/debug-etc/config.yml
Fixes DD-1036
* Added documentation about how to preparte dev environment.
* Corrected default `config.yml` for dev.
* Upgraded parent pom to snapshot version of upgraded parent
(Add links)
*
=> DD-1036 Upgrade DropWizard

pom.xml, src/main/scala/nl.knaw.dans.easy.dd2d/DatasetCreator.scala, src/main/scala/nl.knaw.dans.easy.dd2d/DatasetEditor.scala, src/test/java/nl/knaw/dans/ingest/core/MetadataObjectMapper.java, src/test/scala/nl.knaw.dans.easy.dd2d/DepositToDataverseMapperSpec.scala, src/test/scala/nl.knaw.dans.easy.dd2d/TestSupportFixture.scala, src/test/scala/nl.knaw.dans.easy.dd2d/fieldbuilders/CompoundFieldBuilderSpec.scala, src/test/scala/nl.knaw.dans.easy.dd2d/mapping/DatesOfCollectionSpec.scala, src/test/scala/nl.knaw.dans.easy.dd2d/mapping/DcxDaiAuthorSpec.scala, src/test/scala/nl.knaw.dans.easy.dd2d/mapping/DcxDaiOrganizationSpec.scala, src/test/scala/nl.knaw.dans.easy.dd2d/mapping/DepositPropertiesVaultMetadataSpec.scala, src/test/scala/nl.knaw.dans.easy.dd2d/mapping/DescriptionSpec.scala, src/test/scala/nl.knaw.dans.easy.dd2d/mapping/IdentifierSpec.scala, src/test/scala/nl.knaw.dans.easy.dd2d/mapping/SpatialBoxSpec.scala, src/test/scala/nl.knaw.dans.easy.dd2d/mapping/SpatialPointSpec.scala
Fixes DD-999drop json serializations introduced as detours during hybrid library phase
(Add links)
*
=> DD-999 json serializations

docs/dev.md, src/main/java/nl/knaw/dans/ingest/core/service/mapping/DcxDaiAuthor.java, src/main/java/nl/knaw/dans/ingest/core/service/mapping/DcxDaiOrganization.java, src/main/java/nl/knaw/dans/ingest/core/service/mapping/IdUriHelper.java, src/test/java/nl/knaw/dans/ingest/core/service/mapping/DcxDaiAuthorTest.java, src/test/java/nl/knaw/dans/ingest/core/service/mapping/DcxDaiOrganizationTest.java, src/test/java/nl/knaw/dans/ingest/core/service/mapping/IdUriHelperTest.java
Fixes DD-1164: reduce author URI-s to ID-s
* reduce author URI-s to ID-s
* elaborated documentation to run a manual test
(Add links)
*
=> DD-1164: reduce author URI-s to ID-s

src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapper.java, src/main/java/nl/knaw/dans/ingest/core/service/mapper/mapping/Author.java, src/main/java/nl/knaw/dans/ingest/core/service/mapper/mapping/Description.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/MappingIntegrationTest.java
Fixes DD-1216: part 1 - descriptionType Other to authorName
(Add links)
*
=> DD-1216: part 1 - descriptionType Other to authorName

src/main/java/nl/knaw/dans/ingest/core/service/mapper/mapping/InCollection.java
=> DD-1244: valueUri -> valueURI

src/main/java/nl/knaw/dans/ingest/core/service/Deposit.java, src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapper.java, src/test/java/nl/knaw/dans/ingest/core/service/DepositTest.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapperTest.java, src/test/resources/xml/dataset-simple.xml
=> Fix doi:null or doi: values from appearing

src/main/java/nl/knaw/dans/ingest/core/service/mapper/builder/CitationFieldBuilder.java, src/main/java/nl/knaw/dans/ingest/core/service/mapper/mapping/Audience.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/MappingIntegrationTest.java
Fixes DD-1265: subject other at most once and if nothing else
(Add links)
*
=> DD-1265: subject other at most once and if nothing else

src/test/java/nl/knaw/dans/ingest/core/service/mapper/MappingIntegrationTest.java
Fixes DD-1265 review: parameterized ddm profile
(Add links)
*
=> DD-1265 review: parameterized ddm profile

src/main/java/nl/knaw/dans/ingest/core/service/DepositIngestTask.java, src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapper.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapperTest.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/MappingIntegrationTest.java
Replaces #61 which had too many conflicts with `master` to merge directly.
=> DD-1216 copy of @jo-pol's code with master merged

pom.xml, src/main/java/nl/knaw/dans/ingest/core/service/DansBagValidator.java, src/main/java/nl/knaw/dans/ingest/core/service/DansBagValidatorImpl.java, src/main/java/nl/knaw/dans/ingest/core/service/DepositIngestTask.java, src/main/java/nl/knaw/dans/ingest/core/service/DepositMigrationTask.java
=> Remove level from validate command

src/main/java/nl/knaw/dans/ingest/core/service/DatasetEditor.java, src/main/java/nl/knaw/dans/ingest/core/service/ZipFileHandler.java
Fixes DD-1224: zip original metadata
(Add links)
*
=> DD-1224: zip original metadata

src/main/java/nl/knaw/dans/ingest/core/service/DatasetEditor.java, src/main/java/nl/knaw/dans/ingest/core/service/DatasetUpdater.java, src/main/java/nl/knaw/dans/ingest/core/service/DepositIngestTask.java, src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapper.java, src/main/java/nl/knaw/dans/ingest/core/service/mapper/mapping/AccessRights.java, src/main/java/nl/knaw/dans/ingest/core/service/mapper/mapping/FileElement.java, src/main/java/nl/knaw/dans/ingest/core/service/mapper/mapping/License.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapperTest.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/MappingIntegrationTest.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/mapping/AccessRightsTest.java, src/test/resources/xml/dataset-simple.xml
=> Implementing missing mappings from mapping spreadsheet

src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapper.java, src/main/java/nl/knaw/dans/ingest/core/service/mapper/mapping/Subject.java
=> Fixed bugs in mapping

src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapper.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/CitationMetadataFromProfileTest.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/MappingIntegrationTest.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/MappingIntegrationTestHelper.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/MappingTestHelper.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/RightsMetadataTest.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/mapping/AuthorTest.java
Fixes DD-1280: 
* metadata-block rights
* metadata-block citation as far as the source is ddm/profile
(Add links)
*
=> DD-1280: unit test for mapping of rights and profile

src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapper.java
Fixes DD-1267
For the 15 original Dublin Core terms look in both DC and DCTERMS namespaces.
=> DD-1267 Look for dublin core elements in both DC and DCTERMS namespaces

src/main/java/nl/knaw/dans/ingest/core/service/mapper/mapping/FileElement.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/mapping/FileElementTest.java
=> Added test and removed + from regex

docs/dev.md
=> NON JIRA ISSUE: updated how to start dd-validate-dans-bag

src/main/java/nl/knaw/dans/ingest/core/domain/Deposit.java, src/main/java/nl/knaw/dans/ingest/core/domain/VaultMetadata.java, src/main/java/nl/knaw/dans/ingest/core/service/DepositIngestTask.java, src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapper.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/CitationMetadataFromDcmiTest.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapperTest.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/MappingTestHelper.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/RightsMetadataTest.java
NO JIRA
Fixed the code that fills in the vault metadata block. 
=> Fix vault md rules

src/main/assembly/dist/cfg/config.yml, src/main/java/nl/knaw/dans/ingest/core/config/IngestFlowConfig.java, src/main/java/nl/knaw/dans/ingest/core/service/DepositIngestTaskFactoryBuilder.java, src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapper.java, src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapperFactory.java, src/test/java/nl/knaw/dans/ingest/core/DepositStartImportTaskWrapperTest.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/CitationMetadataFromDcmiTest.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/DansDataVaultMetadataTest.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapperTest.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/MappingTestHelper.java, src/test/resources/debug-etc/config.yml, src/test/resources/test-etc/config.yml
Fixes DD-1402: configure and filter fields
Two test will fail after un-comment of https://github.com/DANS-KNAW/dd-ingest-flow/blob/d4ab90024677151c12c7332c7f77c79bcbec35e5/src/test/resources/test-etc/config.yml#L17-L18
(Add links)
=> DD-1402: configure and filter fields

pom.xml, src/main/java/nl/knaw/dans/ingest/core/service/DansBagValidator.java, src/main/java/nl/knaw/dans/ingest/core/service/DansBagValidatorImpl.java, src/main/java/nl/knaw/dans/ingest/core/service/DepositIngestTask.java, src/main/java/nl/knaw/dans/ingest/core/service/DepositMigrationTask.java, src/test/java/nl/knaw/dans/ingest/core/service/DepositIngestTaskTest.java
Fixes DD-1414
Using generated client for dd-validate-dans-bag
=> DD-1414 Using generated client for dd-validate-dans-bag

docs/dev.md, src/main/assembly/dist/cfg/config.yml, src/main/java/nl/knaw/dans/ingest/core/config/IngestFlowConfig.java, src/main/java/nl/knaw/dans/ingest/core/service/DatasetCreator.java, src/main/java/nl/knaw/dans/ingest/core/service/DatasetEditor.java, src/main/java/nl/knaw/dans/ingest/core/service/DatasetUpdater.java, src/main/java/nl/knaw/dans/ingest/core/service/DepositIngestTask.java, src/main/java/nl/knaw/dans/ingest/core/service/DepositIngestTaskFactory.java, src/main/java/nl/knaw/dans/ingest/core/service/DepositIngestTaskFactoryBuilder.java, src/main/java/nl/knaw/dans/ingest/core/service/DepositMigrationTask.java, src/test/java/nl/knaw/dans/ingest/ConfigurationTest.java, src/test/java/nl/knaw/dans/ingest/core/DepositStartImportTaskWrapperTest.java, src/test/java/nl/knaw/dans/ingest/core/service/DatasetEditorTest.java, src/test/java/nl/knaw/dans/ingest/core/service/DepositIngestTaskTest.java, src/test/resources/debug-etc/config.yml, src/test/resources/examples/valid-easy-submitted/example-bag-medium/bag-info.txt, src/test/resources/test-etc/config.yml, src/test/resources/unit-test-config.yml
=> DD-1421: Added vaultMetadataKey config and using it with updateMetadata

src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapper.java, src/main/java/nl/knaw/dans/ingest/core/service/mapper/builder/CitationFieldBuilder.java, src/main/java/nl/knaw/dans/ingest/core/service/mapper/mapping/Description.java, src/test/java/nl/knaw/dans/ingest/core/service/mapper/CitationMetadataFromDcmiTest.java
=> Series field is a multi-value field in v5.14

pom.xml, src/main/java/nl/knaw/dans/ingest/DdIngestFlowApplication.java, src/main/java/nl/knaw/dans/ingest/DdIngestFlowConfiguration.java
Fixes DD-1381 Upgrade microservices to DropWizard 3
(Add links)
*
=> DD-1381 Upgrade microservices to DropWizard 3

src/main/java/nl/knaw/dans/ingest/core/service/mapper/DepositToDvDatasetMetadataMapper.java
Fixes DD-1510
* Removes one `if` statement.
* Import a PAN deposit through SWORD and check that the artifact shows up in the metadata.
@DANS-KNAW/core-systems
=> DD-1510 Support old ABR term URIs for PAN
